let data = [{
  "nodeName": "首站换执站1",
  "uid": "a0223d12-469c-42e5-91ff-c2308469c0e7",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "HS1",
  "cid": "1"
}, {
  "nodeName": "六中换热站",
  "uid": "b42529ad-1e38-44ba-a970-2dffaac0e989",
  "nodeType": "H",
  "parent_V_Id": "HD",
  "nodeId": "H1",
  "cid": "2"
}, {
  "nodeName": "变径连接点H1-A",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "H1-A",
  "cid": ""
}, {
  "nodeName": "金华苑换热站",
  "uid": "266cf4b6-4028-4b75-9d48-251aa1ed811f",
  "nodeType": "H",
  "parent_V_Id": "HD",
  "nodeId": "H2",
  "cid": "2"
}, {
  "nodeName": "御龙湾换热站",
  "uid": "a3a6ca91-913c-45ac-bd3e-71fbb3c6c402",
  "nodeType": "H",
  "parent_V_Id": "HD",
  "nodeId": "H3",
  "cid": "2"
}, {
  "nodeName": "闫冀堡树换热站",
  "uid": "f30b9873-3cc4-4de2-afd7-20938b2e05fd",
  "nodeType": "H",
  "parent_V_Id": "HD",
  "nodeId": "H4",
  "cid": "1"
}, {
  "nodeName": "棚户区B区换热站",
  "uid": "4ae724d3-c0cb-46b3-9c50-9ac9c08b3a1d",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H5",
  "cid": "1"
}, {
  "nodeName": "棚户区一期换热站",
  "uid": "ce01bdbc-5e43-44b7-b6fc-2576732455d2",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H6",
  "cid": "1"
}, {
  "nodeName": "安逸村换热站",
  "uid": "73b46daf-d42d-48c3-9488-2cee279fec41",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H7",
  "cid": "1"
}, {
  "nodeName": "梁吉村换热站",
  "uid": "46104474-a8e5-4b32-b69f-f8758774b784",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H8",
  "cid": "1"
}, {
  "nodeName": "绿都二期换热站",
  "uid": "409e2b31-8d6d-4733-8004-6089a5dda855",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H9",
  "cid": "1"
}, {
  "nodeName": "梁吉村东换热站",
  "uid": "4d94f835-7c59-4ad0-a39d-2a90f1f80d79",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H10",
  "cid": "1"
}, {
  "nodeName": "李家堡换热站(纬四路)",
  "uid": "ac0d9010-bba2-4d53-91b3-029ae5207345",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H11",
  "cid": "1"
}, {
  "nodeName": "赵家堡村换热站",
  "uid": "ab7885ae-099d-4b00-a3ae-19897462f77a",
  "nodeType": "H",
  "parent_V_Id": "HC",
  "nodeId": "H12",
  "cid": "2"
}, {
  "nodeName": "李家堡村换热站(纬三路)",
  "uid": "e1f35436-a1ae-41d0-bd29-b893afd318f2",
  "nodeType": "H",
  "parent_V_Id": "HC",
  "nodeId": "H13",
  "cid": "2"
}, {
  "nodeName": "残联换热站",
  "uid": "未查询到",
  "nodeType": "H",
  "parent_V_Id": "HC",
  "nodeId": "H14",
  "cid": "2"
}, {
  "nodeName": "韩屯村南换热站",
  "uid": "096715ab-702c-44b1-8989-0317178c48f1",
  "nodeType": "H",
  "parent_V_Id": "HC",
  "nodeId": "H15",
  "cid": "2"
}, {
  "nodeName": "韩屯村北换热站",
  "uid": "747ed9de-4caa-494e-aa1d-8008d501f8e0",
  "nodeType": "H",
  "parent_V_Id": "HC",
  "nodeId": "H16",
  "cid": "2"
}, {
  "nodeName": "亚泰苑换热站",
  "uid": "ef1757e3-06cd-43b1-8cc3-d088b50065e7",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H17",
  "cid": "1"
}, {
  "nodeName": "会计事务所换热站",
  "uid": "0a3e11a5-dca8-461f-b168-7ca7c2aa3122",
  "nodeType": "H",
  "parent_V_Id": "HB",
  "nodeId": "H18",
  "cid": "2"
}, {
  "nodeName": "嘉禾园换热站",
  "uid": "441aabd9-43a9-4395-b596-f94ee371c9a5",
  "nodeType": "H",
  "parent_V_Id": "HB",
  "nodeId": "H19",
  "cid": "2"
}, {
  "nodeName": "安居苑换热站",
  "uid": "a58ad4ff-7488-44de-aeda-7056c6bb667a",
  "nodeType": "H",
  "parent_V_Id": "HB",
  "nodeId": "H20",
  "cid": "2"
}, {
  "nodeName": "安泰换热站",
  "uid": "c5b9bb35-6deb-4066-b638-df1920064a40",
  "nodeType": "H",
  "parent_V_Id": "HA",
  "nodeId": "H21",
  "cid": "2"
}, {
  "nodeName": "安康嘉园换热站",
  "uid": "0946f809-6e40-4d0f-bd98-032ce57b105d",
  "nodeType": "H",
  "parent_V_Id": "HA",
  "nodeId": "H22",
  "cid": "2"
}, {
  "nodeName": "上站村换热站",
  "uid": "cc36c170-a62b-4d58-a53d-df4e8b628809",
  "nodeType": "H",
  "parent_V_Id": "HA",
  "nodeId": "H23",
  "cid": "2"
}, {
  "nodeName": "顺康换热站",
  "uid": "7117c79a-b3b9-450a-8b82-fbbf3af271da",
  "nodeType": "H",
  "parent_V_Id": "HA",
  "nodeId": "H24",
  "cid": "2"
}, {
  "nodeName": "公安局换热站",
  "uid": "fe5e3396-9059-417c-88d7-4aa6448c641e",
  "nodeType": "H",
  "parent_V_Id": "HA",
  "nodeId": "H25",
  "cid": "2"
}, {
  "nodeName": "蓉和菀换热站",
  "uid": "ee8daff2-5a52-443d-bfb3-6b9786b91894",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H26",
  "cid": "1"
}, {
  "nodeName": "气象局换热站",
  "uid": "未查询到",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H27",
  "cid": "1"
}, {
  "nodeName": "嘉欣园高区换热站",
  "uid": "b15bb406-e07f-41ef-9994-9d94acbad115",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H28_H",
  "cid": "1"
}, {
  "nodeName": "嘉欣园中区换热站",
  "uid": "7a7fe618-214c-477d-bcae-1fd003fd47a0",
  "nodeType": "",
  "parent_V_Id": "",
  "nodeId": "H28_M",
  "cid": ""
}, {
  "nodeName": "嘉欣园低区换热站",
  "uid": "18fe049d-76ee-40f9-b0a9-00a47f2e1fd3",
  "nodeType": "",
  "parent_V_Id": "",
  "nodeId": "H28_L",
  "cid": ""
}, {
  "nodeName": "三道河换热站",
  "uid": "4f1e3458-8f71-4544-ad28-368a35bf55d2",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H29",
  "cid": "1"
}, {
  "nodeName": "新体育场换热站",
  "uid": "未查询到",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H30",
  "cid": "1"
}, {
  "nodeName": "宋古换热站",
  "uid": "b479cee0-f702-462c-afcc-dde60e1dae26",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H31",
  "cid": "1"
}, {
  "nodeName": "南张家庄换热站",
  "uid": "9fa0b4ed-89bc-4691-81b7-b1e091e5467b",
  "nodeType": "H",
  "parent_V_Id": "HJ",
  "nodeId": "H32",
  "cid": "2"
}, {
  "nodeName": "宋古村换热站",
  "uid": "151f37ea-b0cf-4d33-8c23-8ecf8a4950dd",
  "nodeType": "H",
  "parent_V_Id": "HJ",
  "nodeId": "H33",
  "cid": "2"
}, {
  "nodeName": "宋古驾校换热站",
  "uid": "38d25e5f-37c9-472d-9a91-ddb7ae0229ee",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H34",
  "cid": "1"
}, {
  "nodeName": "马女村换热站",
  "uid": "7a6c83a1-6668-45a8-994c-98ccc523fc85",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H35",
  "cid": "1"
}, {
  "nodeName": "绵山一中换热站",
  "uid": "94768ab2-55bd-44e7-a66f-3bad8e7ca0cd",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H36",
  "cid": "3"
}, {
  "nodeName": "南靳屯村换热站",
  "uid": "c1ff3cdb-4b8a-4061-9c61-b9a863f9c92a",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H37",
  "cid": "3"
}, {
  "nodeName": "交警队换热站",
  "uid": "a274d704-5bbd-498d-8c3b-f34d0c94a312",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H38",
  "cid": "3"
}, {
  "nodeName": "后党峪小区换热站",
  "uid": "5780ca0f-8314-4ccc-adc5-6aae77a96678",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H39",
  "cid": "3"
}, {
  "nodeName": "粮食局直属库换热站",
  "uid": "2d69300e-c87b-41c9-af27-9db83c13124a",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H40",
  "cid": "3"
}, {
  "nodeName": "东南办事处换热站",
  "uid": "be18e6c9-f444-45df-afb0-f97ba60d8021",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H41",
  "cid": "3"
}, {
  "nodeName": "定阳路南换热站",
  "uid": "75ba66df-ed3f-41ae-9a8f-67986595172c",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H42",
  "cid": "3"
}, {
  "nodeName": "石油公司换热站",
  "uid": "500deff6-cd87-44fb-86e6-c1fc418afb30",
  "nodeType": "H",
  "parent_V_Id": "HI-3",
  "nodeId": "H43",
  "cid": "3"
}, {
  "nodeName": "电碳厂换热站",
  "uid": "dfaa38e4-b56e-408f-8eeb-cf62044ad4e5",
  "nodeType": "H",
  "parent_V_Id": "HI-2",
  "nodeId": "H44",
  "cid": "3"
}, {
  "nodeName": "石河村换热站",
  "uid": "b6f29c99-45ab-45f6-a96d-35043e596ebf",
  "nodeType": "H",
  "parent_V_Id": "HI-2",
  "nodeId": "H45",
  "cid": "3"
}, {
  "nodeName": "电杆厂换热站",
  "uid": "f4f44852-3895-4138-a860-fadf602486b7",
  "nodeType": "H",
  "parent_V_Id": "HI-1",
  "nodeId": "H46",
  "cid": "3"
}, {
  "nodeName": "朝阳路换热站",
  "uid": "6e704d46-8f69-4a08-a2e9-54878ac543e9",
  "nodeType": "H",
  "parent_V_Id": "HI-1",
  "nodeId": "H47",
  "cid": "3"
}, {
  "nodeName": "永康换热站",
  "uid": "f0468692-ae50-44a0-a0c5-3f6aec9d7f27",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H48",
  "cid": "1"
}, {
  "nodeName": "顺城关换热站",
  "uid": "324f589d-f646-446b-98c2-c2aca2ee97fc",
  "nodeType": "H",
  "parent_V_Id": "HH",
  "nodeId": "H49",
  "cid": "2"
}, {
  "nodeName": "彦泰换热站",
  "uid": "32ee3f1b-8bdb-4ee5-87c0-a8c8c081e31b",
  "nodeType": "H",
  "parent_V_Id": "HH",
  "nodeId": "H50",
  "cid": "2"
}, {
  "nodeName": "介休一中换热站",
  "uid": "9dee2c27-b1c6-4950-ba24-d9408fa50366",
  "nodeType": "H",
  "parent_V_Id": "HH-1",
  "nodeId": "H51",
  "cid": "3"
}, {
  "nodeName": "变径连接点H51-A",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "H51-A",
  "cid": ""
}, {
  "nodeName": "变径连接点H51-B",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "H51-B",
  "cid": ""
}, {
  "nodeName": "变径连接点H51-C",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "H51-C",
  "cid": ""
}, {
  "nodeName": "泓达小区换热站",
  "uid": "f7cd7edf-3513-445e-b072-6688f22889f0",
  "nodeType": "H",
  "parent_V_Id": "HH-1",
  "nodeId": "H52",
  "cid": "3"
}, {
  "nodeName": "二中换热站",
  "uid": "7c991498-0bbe-44ea-8462-86ad11cccd61",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H53",
  "cid": "3"
}, {
  "nodeName": "馨苑小区换热站",
  "uid": "88a89d45-0831-4c06-81ae-9033440f9e0d",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H54",
  "cid": "3"
}, {
  "nodeName": "邮政局换热站",
  "uid": "4ffcdaed-d332-498d-8309-e0a26341ca46",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H55",
  "cid": "3"
}, {
  "nodeName": "盛华丽苑换热站",
  "uid": "4fdfa4cf-3d74-47a7-a327-d90976e19af9",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H56",
  "cid": "3"
}, {
  "nodeName": "人民医院换热站",
  "uid": "未查询到",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H57",
  "cid": "3"
}, {
  "nodeName": "环保局换热站",
  "uid": "9f34e840-dd46-4ba8-83c2-22f0a9df2205",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H58",
  "cid": "3"
}, {
  "nodeName": "城建局换热站",
  "uid": "80c1ed83-8d91-42e9-bfa7-97ab229587c3",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H59",
  "cid": "3"
}, {
  "nodeName": "北坛小学换热站",
  "uid": "0054fd1f-7df7-4c0f-b788-40bae223920c",
  "nodeType": "H",
  "parent_V_Id": "HH-2",
  "nodeId": "H60",
  "cid": "3"
}, {
  "nodeName": "药材公司换热站",
  "uid": "19ed6586-2e9b-47c6-bb36-76c1fa54d4e3",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H61",
  "cid": "2"
}, {
  "nodeName": "城关一院换热站",
  "uid": "8f8ba1df-0fc1-42ac-aa10-f874f9d168eb",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H62",
  "cid": "2"
}, {
  "nodeName": "秀南怡苑换热站",
  "uid": "08f2ed60-4b7e-4a3d-acb4-e4ea62c4c2d2",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H63",
  "cid": "2"
}, {
  "nodeName": "物资机关换热站",
  "uid": "fb8877c7-ec5c-46d2-91af-dde97eb81ef2",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H64",
  "cid": "2"
}, {
  "nodeName": "中仁换热站",
  "uid": "246fa455-8dcc-4cbe-8286-26439feb7d7a",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H65",
  "cid": "2"
}, {
  "nodeName": "一品天下换热站",
  "uid": "13565321-edf0-4c73-a6fd-b96db89be16f",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H66",
  "cid": "2"
}, {
  "nodeName": "矿务局供应处换热站",
  "uid": "92d56709-b24e-4bcd-87a8-d21224221cf7",
  "nodeType": "H",
  "parent_V_Id": "HG",
  "nodeId": "H67",
  "cid": "2"
}, {
  "nodeName": "铁亮大厦换热站",
  "uid": "3b4ec881-6dfa-496c-80c0-d614d40fb4c7",
  "nodeType": "H",
  "parent_V_Id": "HG-1",
  "nodeId": "H68",
  "cid": "3"
}, {
  "nodeName": "车站二区换热站",
  "uid": "2929b3ad-9170-45be-bc14-77ad3f0d656b",
  "nodeType": "H",
  "parent_V_Id": "HG-1",
  "nodeId": "H69",
  "cid": "3"
}, {
  "nodeName": "二运换热站",
  "uid": "05a5d05e-fc3d-4557-afba-dceffc0bb5f1",
  "nodeType": "H",
  "parent_V_Id": "HG-2",
  "nodeId": "H70",
  "cid": "3"
}, {
  "nodeName": "矿务局医院换热站",
  "uid": "bdaa7ce8-d145-470e-a3ac-d9f7f1cf1033",
  "nodeType": "H",
  "parent_V_Id": "HG-2",
  "nodeId": "H71",
  "cid": "3"
}, {
  "nodeName": "富康苑换热站",
  "uid": "33bbc8b8-e2d3-4e42-807d-ea8513621642",
  "nodeType": "H",
  "parent_V_Id": "HG-2",
  "nodeId": "H72",
  "cid": "3"
}, {
  "nodeName": "电碳厂换热站(宿舍)",
  "uid": "e8c17621-8906-451c-b196-26e4cfe5fe0f",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H73",
  "cid": "1"
}, {
  "nodeName": "城隍庙换热站",
  "uid": "b986e515-d4d5-48f4-b67b-a39fea6fd9f2",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H74",
  "cid": "1"
}, {
  "nodeName": "南大街换热站",
  "uid": "939e2f11-92b3-4a3a-81aa-39b8078500fd",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H75",
  "cid": "1"
}, {
  "nodeName": "党校换热站",
  "uid": "6b2a0c3a-30db-4886-a8da-65c0753aa30a",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H76",
  "cid": "1"
}, {
  "nodeName": "体委换热站",
  "uid": "52cecd73-bf64-4efd-95bf-e1f22362fc3b",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H77",
  "cid": "1"
}, {
  "nodeName": "中行换热站",
  "uid": "b113143c-8e53-459e-a533-06dcb55df3fc",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H78",
  "cid": "1"
}, {
  "nodeName": "矿务局机关换热站",
  "uid": "addf3e51-f873-41cf-b6db-7e7122f4b3b9",
  "nodeType": "H",
  "parent_V_Id": "HF",
  "nodeId": "H79",
  "cid": "2"
}, {
  "nodeName": "矿务局技校换热站",
  "uid": "d11c3995-9c4e-4723-8056-9c66bc0faeb0",
  "nodeType": "H",
  "parent_V_Id": "HF",
  "nodeId": "H80",
  "cid": "2"
}, {
  "nodeName": "农发行换热站",
  "uid": "8f6e3431-e8e1-44c3-945e-da4915cefe73",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H81",
  "cid": "1"
}, {
  "nodeName": "景泰换热站",
  "uid": "7cb048be-f7c5-4555-8718-5b23b02b0333",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H82",
  "cid": "1"
}, {
  "nodeName": "水泵厂换热站",
  "uid": "296bd631-fb9d-49ec-a8e8-e93139f0c713",
  "nodeType": "H",
  "parent_V_Id": "",
  "nodeId": "H83",
  "cid": "1"
}, {
  "nodeName": "无机盐厂换热站",
  "uid": "73826f02-776d-4267-83ef-0fa34464b19d",
  "nodeType": "H",
  "parent_V_Id": "HE",
  "nodeId": "H84",
  "cid": "2"
}, {
  "nodeName": "棚户区二期_高区换热站",
  "uid": "3249afaf-82a1-459c-919b-dbc4a995cb4b",
  "nodeType": "H",
  "parent_V_Id": "HE",
  "nodeId": "H85_H",
  "cid": "2"
}, {
  "nodeName": "棚户区二期_低区换热站",
  "uid": "f28b5a31-2e15-4d36-a7e2-6d5aaf3a0159",
  "nodeType": "",
  "parent_V_Id": "",
  "nodeId": "H85_L",
  "cid": ""
}, {
  "nodeName": "消防队换热站",
  "uid": "74324b6a-cabe-4b37-886b-59e1874fb764",
  "nodeType": "H",
  "parent_V_Id": "HE",
  "nodeId": "H86",
  "cid": "2"
}, {
  "nodeName": "绵山墅高区换热站",
  "uid": "408e509b-e95f-4f60-9f81-b18cb421f58d",
  "nodeType": "H",
  "parent_V_Id": "HE",
  "nodeId": "H87_H",
  "cid": "2"
}, {
  "nodeName": "绵山墅低区换热站",
  "uid": "afd78e0d-9684-4ca8-810c-9af8d9b9dd09",
  "nodeType": "",
  "parent_V_Id": "",
  "nodeId": "H87_L",
  "cid": ""
}, {
  "nodeName": "纸厂换热站",
  "uid": "d5fddb54-14d1-4924-971c-0afaec4f618f",
  "nodeType": "H",
  "parent_V_Id": "HE",
  "nodeId": "H88",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站A",
  "uid": "f2f87225-1c9b-5430-af88-fbf879a5f59a",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HA",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站B",
  "uid": "2f361cbb-05cf-5bf8-a3dc-2312eea04ade",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HB",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站C",
  "uid": "83843a77-0a15-5c5f-88a7-8c00df9ea189",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HC",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站D",
  "uid": "f30bcb1f-2f7c-5e5f-bced-46be08115864",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HD",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站E",
  "uid": "c9f049ee-d684-503c-b8de-d64aa8c237f6",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HE",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站F",
  "uid": "ad5cc6b3-f4fe-5615-af8b-2d47414e5944",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HF",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站G",
  "uid": "fb415d20-6328-5893-be5e-4180eff76933",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HG",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站G-1",
  "uid": "611c37f2-d865-5116-8ac0-c7d9c8614628",
  "nodeType": "V",
  "parent_V_Id": "HG",
  "nodeId": "HG-1",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站G-2",
  "uid": "6a926cba-e864-578a-b4a8-99a0695fbc62",
  "nodeType": "V",
  "parent_V_Id": "HG",
  "nodeId": "HG-2",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站H",
  "uid": "c446a1a6-4783-565c-a94b-01b71cae8a46",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HH",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站H-1",
  "uid": "0ab48e8b-a484-5ea0-b9f1-198bb04052a3",
  "nodeType": "V",
  "parent_V_Id": "HH",
  "nodeId": "HH-1",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站H-2",
  "uid": "f5428dcf-562b-576b-a8c3-f0e28293af47",
  "nodeType": "V",
  "parent_V_Id": "HH",
  "nodeId": "HH-2",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站I",
  "uid": "52fa0036-775b-5761-b712-e080374bcee2",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HI",
  "cid": "1"
}, {
  "nodeName": "虚拟换热站I-1",
  "uid": "c4e5448e-942c-5f7a-a409-dfcf6125744c",
  "nodeType": "V",
  "parent_V_Id": "HI",
  "nodeId": "HI-1",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站I-2",
  "uid": "5cc8cfbf-77c1-5dd8-8646-7e5e46b49c3e",
  "nodeType": "V",
  "parent_V_Id": "HI",
  "nodeId": "HI-2",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站I-3",
  "uid": "04b630b4-8ef2-5f40-a760-f6698aab8225",
  "nodeType": "V",
  "parent_V_Id": "HI",
  "nodeId": "HI-3",
  "cid": "2"
}, {
  "nodeName": "虚拟换热站J",
  "uid": "df04da0d-e5f1-5587-badb-8ecd246484f2",
  "nodeType": "V",
  "parent_V_Id": "",
  "nodeId": "HJ",
  "cid": "1"
}, {
  "nodeName": "管网供水节点1",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P1",
  "cid": ""
}, {
  "nodeName": "变径连接点P1-A",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "P1-A",
  "cid": ""
}, {
  "nodeName": "管网供水节点2",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P2",
  "cid": ""
}, {
  "nodeName": "管网供水节点3",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P3",
  "cid": ""
}, {
  "nodeName": "管网供水节点4",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P4",
  "cid": ""
}, {
  "nodeName": "管网供水节点5",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P5",
  "cid": ""
}, {
  "nodeName": "管网供水节点6",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P6",
  "cid": ""
}, {
  "nodeName": "变径连接点P6-A",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "P6-A",
  "cid": ""
}, {
  "nodeName": "管网供水节点7",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P7",
  "cid": ""
}, {
  "nodeName": "管网供水节点8",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P8",
  "cid": ""
}, {
  "nodeName": "管网供水节点9",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P9",
  "cid": ""
}, {
  "nodeName": "管网供水节点10",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P10",
  "cid": ""
}, {
  "nodeName": "管网供水节点11",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P11",
  "cid": ""
}, {
  "nodeName": "管网供水节点12",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P12",
  "cid": ""
}, {
  "nodeName": "管网供水节点13",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P13",
  "cid": ""
}, {
  "nodeName": "管网供水节点14",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P14",
  "cid": ""
}, {
  "nodeName": "管网供水节点15",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P15",
  "cid": ""
}, {
  "nodeName": "管网供水节点16",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P16",
  "cid": ""
}, {
  "nodeName": "管网供水节点17",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P17",
  "cid": ""
}, {
  "nodeName": "管网供水节点18",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P18",
  "cid": ""
}, {
  "nodeName": "管网供水节点19",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P19",
  "cid": ""
}, {
  "nodeName": "管网供水节点20",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P20",
  "cid": ""
}, {
  "nodeName": "管网供水节点21",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P21",
  "cid": ""
}, {
  "nodeName": "管网供水节点22",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P22",
  "cid": ""
}, {
  "nodeName": "管网供水节点23",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P23",
  "cid": ""
}, {
  "nodeName": "管网供水节点24",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P24",
  "cid": ""
}, {
  "nodeName": "管网供水节点25",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P25",
  "cid": ""
}, {
  "nodeName": "管网供水节点26",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P26",
  "cid": ""
}, {
  "nodeName": "管网供水节点27",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P27",
  "cid": ""
}, {
  "nodeName": "管网供水节点28",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P28",
  "cid": ""
}, {
  "nodeName": "管网供水节点29",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P29",
  "cid": ""
}, {
  "nodeName": "管网供水节点30",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P30",
  "cid": ""
}, {
  "nodeName": "管网供水节点31",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P31",
  "cid": ""
}, {
  "nodeName": "管网供水节点32",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P32",
  "cid": ""
}, {
  "nodeName": "管网供水节点33",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P33",
  "cid": ""
}, {
  "nodeName": "管网供水节点34",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P34",
  "cid": ""
}, {
  "nodeName": "管网供水节点35",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P35",
  "cid": ""
}, {
  "nodeName": "管网供水节点36",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P36",
  "cid": ""
}, {
  "nodeName": "管网供水节点37",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P37",
  "cid": ""
}, {
  "nodeName": "管网供水节点38",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P38",
  "cid": ""
}, {
  "nodeName": "管网供水节点39",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P39",
  "cid": ""
}, {
  "nodeName": "管网供水节点40",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P40",
  "cid": ""
}, {
  "nodeName": "管网供水节点41",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P41",
  "cid": ""
}, {
  "nodeName": "管网供水节点42",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P42",
  "cid": ""
}, {
  "nodeName": "管网供水节点43",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P43",
  "cid": ""
}, {
  "nodeName": "管网供水节点44",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P44",
  "cid": ""
}, {
  "nodeName": "管网供水节点45",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P45",
  "cid": ""
}, {
  "nodeName": "管网供水节点46",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P46",
  "cid": ""
}, {
  "nodeName": "管网供水节点47",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P47",
  "cid": ""
}, {
  "nodeName": "管网供水节点48",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P48",
  "cid": ""
}, {
  "nodeName": "管网供水节点49",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P49",
  "cid": ""
}, {
  "nodeName": "管网供水节点50",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P50",
  "cid": ""
}, {
  "nodeName": "管网供水节点51",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P51",
  "cid": ""
}, {
  "nodeName": "管网供水节点52",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P52",
  "cid": ""
}, {
  "nodeName": "管网供水节点53",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P53",
  "cid": ""
}, {
  "nodeName": "管网供水节点54",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P54",
  "cid": ""
}, {
  "nodeName": "管网供水节点55",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P55",
  "cid": ""
}, {
  "nodeName": "管网供水节点56",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P56",
  "cid": ""
}, {
  "nodeName": "管网供水节点57",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P57",
  "cid": ""
}, {
  "nodeName": "变径连接点P57-A",
  "uid": "",
  "nodeType": "C",
  "parent_V_Id": "",
  "nodeId": "P57-A",
  "cid": ""
}, {
  "nodeName": "管网供水节点58",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P58",
  "cid": ""
}, {
  "nodeName": "管网供水节点59",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P59",
  "cid": ""
}, {
  "nodeName": "管网供水节点60",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P60",
  "cid": ""
}, {
  "nodeName": "管网供水节点61",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P61",
  "cid": ""
}, {
  "nodeName": "管网供水节点62",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P62",
  "cid": ""
}, {
  "nodeName": "管网供水节点63",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P63",
  "cid": ""
}, {
  "nodeName": "管网供水节点64",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P64",
  "cid": ""
}, {
  "nodeName": "管网供水节点65",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P65",
  "cid": ""
}, {
  "nodeName": "管网供水节点66",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P66",
  "cid": ""
}, {
  "nodeName": "管网供水节点67",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P67",
  "cid": ""
}, {
  "nodeName": "管网供水节点68",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P68",
  "cid": ""
}, {
  "nodeName": "管网供水节点69",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P69",
  "cid": ""
}, {
  "nodeName": "管网供水节点70",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P70",
  "cid": ""
}, {
  "nodeName": "管网供水节点71",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P71",
  "cid": ""
}, {
  "nodeName": "管网供水节点72",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P72",
  "cid": ""
}, {
  "nodeName": "管网供水节点73",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P73",
  "cid": ""
}, {
  "nodeName": "管网供水节点74",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P74",
  "cid": ""
}, {
  "nodeName": "管网供水节点75",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P75",
  "cid": ""
}, {
  "nodeName": "管网供水节点76",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P76",
  "cid": ""
}, {
  "nodeName": "管网供水节点77",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P77",
  "cid": ""
}, {
  "nodeName": "管网供水节点78",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P78",
  "cid": ""
}, {
  "nodeName": "管网供水节点79",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P79",
  "cid": ""
}, {
  "nodeName": "管网供水节点80",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P80",
  "cid": ""
}, {
  "nodeName": "管网供水节点81",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P81",
  "cid": ""
}, {
  "nodeName": "管网供水节点82",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P82",
  "cid": ""
}, {
  "nodeName": "管网供水节点83",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P83",
  "cid": ""
}, {
  "nodeName": "管网供水节点84",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P84",
  "cid": ""
}, {
  "nodeName": "管网供水节点85",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P85",
  "cid": ""
}, {
  "nodeName": "管网供水节点86",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P86",
  "cid": ""
}, {
  "nodeName": "管网供水节点87",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P87",
  "cid": ""
}, {
  "nodeName": "管网供水节点88",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P88",
  "cid": ""
}, {
  "nodeName": "管网供水节点89",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P89",
  "cid": ""
}, {
  "nodeName": "管网供水节点90",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P90",
  "cid": ""
}, {
  "nodeName": "管网供水节点91",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P91",
  "cid": ""
}, {
  "nodeName": "管网供水节点92",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P92",
  "cid": ""
}, {
  "nodeName": "管网供水节点93",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P93",
  "cid": ""
}, {
  "nodeName": "管网供水节点94",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P94",
  "cid": ""
}, {
  "nodeName": "管网供水节点95",
  "uid": "",
  "nodeType": "P",
  "parent_V_Id": "",
  "nodeId": "P95",
  "cid": ""
}, {
  "nodeName": "热源供水1",
  "uid": "",
  "nodeType": "S",
  "parent_V_Id": "",
  "nodeId": "S1",
  "cid": ""
}, {"nodeName": "热源供水2", "uid": "", "nodeType": "S", "parent_V_Id": "", "nodeId": "S2", "cid": ""}]

let HData = data.filter(item => {
  return (item.nodeType == 'H' || item.nodeType == 'V') && item.uid != '未查询到'
})

let nodeUids = []
let nodeMap = {}
HData.forEach(item => {
  nodeUids.push(item.uid)
  nodeMap[item.uid] = item
})

// console.log(JSON.stringify(nodeUids))
// console.log(nodeMap)

nodeMap = {}
HData.forEach(item => {
  nodeMap[item.nodeId] = item
})
// console.log(nodeMap)

let res = {}
for(let i in nodeMap) {
  if(nodeMap[i].cid == '1') {
    res[nodeMap[i].uid] = {}
  }
}

for(let i in nodeMap) {
  if(nodeMap[i].cid == '2') {
    if(nodeMap[nodeMap[i].parent_V_Id]) {
      res[nodeMap[nodeMap[i].parent_V_Id].uid][nodeMap[i].uid] = {}
    }else {
      console.error(nodeMap[i])
    }
  }
}

// for(let i in nodeMap) {
//   if(nodeMap[i].cid == '3') {
//     let pUid = nodeMap[nodeMap[i].parent_V_Id].uid
//     let uid = nodeMap[i].uid
//     // console.log(pUid)
//
//     for(let i in res) {
//       if(Object.keys(res[i]).length > 0) {
//         let c = res[i]
//         for(let j in c) {
//           if(j == pUid) {
//             c[j][uid] = {}
//           }
//         }
//       }
//     }
//   }
// }



console.log(res)
