INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09000', 'b49_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"工行宿舍\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b49_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408566, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09001', 'b4_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区13楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b4_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408567, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09002', 'b51_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"市建\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b51_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408568, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09003', 'b9_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b9_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408569, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09004', 'b13_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b13_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408570, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09005', 'b2_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区11楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b2_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408571, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09006', 'b20_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区9楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b20_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408572, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09007', 'b1_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区10楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b1_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408573, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09008', 'b19_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区8楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b19_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408574, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09009', 'b18_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区7楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b18_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408575, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900a', 'b50_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"四中\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b50_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408576, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900b', 'b41_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2007-5楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b41_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408577, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900c', 'b39_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2005-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b39_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408578, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900d', 'b40_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2007-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b40_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408579, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900e', 'b38_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2005-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b38_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408580, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0900f', 'b53_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2007-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b53_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408581, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09010', 'b5_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区16楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b5_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408582, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09011', 'b6_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区17楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b6_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408583, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09012', 'b7_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区18楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b7_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408584, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09013', 'b48_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1996-3西楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b48_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408585, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09014', 'b43_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1996-3东楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b43_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408586, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09015', 'b34_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_北区2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b34_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408587, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09016', 'b35_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_北区3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b35_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408588, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09017', 'b8_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区19楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b8_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408589, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09018', 'b10_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区20楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b10_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408590, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09019', 'b3_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区12楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b3_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408591, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901a', 'b14_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b14_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408592, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901b', 'b42_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1996-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b42_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408593, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901c', 'b11_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区21楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b11_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408594, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901d', 'b12_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区22楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b12_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408595, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901e', 'b17_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区6楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b17_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408596, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0901f', 'b16_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区5楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b16_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408597, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09020', 'b15_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_东区4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b15_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408598, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09021', 'b26_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b26_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408599, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09022', 'b27_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b27_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408600, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09023', 'b28_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b28_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408601, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09024', 'b29_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b29_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408602, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09025', 'b30_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-5楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b30_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408603, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09026', 'b31_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-6楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b31_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408604, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09027', 'b32_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_2000-7楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b32_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408605, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09028', 'b21_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b21_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408606, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09029', 'b22_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b22_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408607, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902a', 'b23_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-5楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b23_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408608, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902b', 'b24_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-6楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b24_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408609, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902c', 'b25_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-7楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b25_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408610, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902d', 'b45_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-1南楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b45_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408611, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902e', 'b44_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-1北楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b44_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408612, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc0902f', 'b47_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-2南楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b47_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408613, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09030', 'b46_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_1999-2北楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b46_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408614, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09031', 'b37_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_北区6楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b37_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408615, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09032', 'b36_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_北区5楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b36_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408616, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09033', 'b52_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"小二层商铺\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b52_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408617, '73ae02a42009000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3b48adc09034', 'b33_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"介坊小区_北区1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:80ca38c47c697152-buildingConfig3:Toolkit:ConditionDerive:b33_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037408618, '73ae02a42009000')