INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a000', 'b1_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2005-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b1_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631820, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a001', 'b2_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2005-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b2_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631821, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a002', 'b3_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_东区23楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b3_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631822, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a003', 'b4_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2007-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b4_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631823, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a004', 'b5_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2002-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b5_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631824, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a005', 'b6_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2001-4东楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b6_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631825, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a006', 'b7_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2001-4西楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b7_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631826, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a007', 'b8_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-4东楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b8_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631827, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a008', 'b9_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-4西楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b9_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631828, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a009', 'b10_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-5东楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b10_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631829, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00a', 'b11_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-5西楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b11_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631830, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00b', 'b12_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-5中楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b12_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631831, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00c', 'b13_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2007-1东楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b13_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631832, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00d', 'b14_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2007-1西楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b14_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631833, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00e', 'b15_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_1996-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b15_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631834, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a00f', 'b16_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_1998-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b16_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631835, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a010', 'b17_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_1998-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b17_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631836, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a011', 'b18_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_1998-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b18_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631837, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a012', 'b19_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_1998-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b19_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631838, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a013', 'b20_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b20_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631839, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a014', 'b21_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b21_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631840, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a015', 'b22_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b22_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631841, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a016', 'b23_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2001-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b23_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631842, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a017', 'b24_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2001-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b24_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631843, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a018', 'b25_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2001-3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b25_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631844, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a019', 'b26_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2002-1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b26_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631845, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01a', 'b27_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2002-4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b27_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631846, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01b', 'b28_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_南区1楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b28_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631847, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01c', 'b29_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_南区2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b29_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631848, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01d', 'b30_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_南区3楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b30_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631849, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01e', 'b31_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_南区4楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b31_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631850, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a01f', 'b32_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_东区24楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b32_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631851, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a020', 'b33_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2002-2楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b33_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631852, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a021', 'b34_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2002-3南\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b34_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631853, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a022', 'b35_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-6楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b35_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631854, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a023', 'b36_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"体委_介坊小区_2004-4中\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b36_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631855, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a024', 'b37_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"幼儿园\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b37_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631856, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a025', 'b38_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"老干部活动中心\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b38_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631857, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a026', 'b39_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"甲班楼\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b39_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631858, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a027', 'b40_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"南区排房\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b40_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631859, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a028', 'b41_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"社区医院\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b41_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631860, '73af2d0bb809000');
INSERT INTO viz_resource_ds_3403c1dd180a000.regulate_config (id, label, description, config, user, modify_time, group_id)
VALUES ('73c3c871f00a029', 'b42_enable_switch', '',
        '{\"title\":\"\",\"isAuto\":false,\"width\":360,\"viewInfo\":{\"title\":\"\",\"fields\":[{\"type\":\"format\",\"property\":\"control_enable\",\"label\":\"市委老干部宿舍\",\"wayOfGetProperty\":\"scada\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"controlInfo\":{\"target\":null,\"scope\":\"smart-edge\",\"fields\":[{\"type\":\"composite\",\"property\":\"smart_operation_tw:5d8eafd0c923b124-buildingConfig3:Toolkit:ConditionDerive:b42_control_enable\",\"label\":\"智能AI\",\"note\":null,\"stepStyle\":\"Symbol\",\"wayOfGetProperty\":\"smart\",\"catalog\":{\"0\":\"关闭\",\"1\":\"开启\"}}]},\"abnormalValidators\":[],\"height\":295}',
        '田苗苗', 1639037631861, '73af2d0bb809000')